
import { useEffect, useState } from "react";
import Heading from "../form/heading/Heading";


const Supporters = () => {
  const [count, setCount] = useState(0);
  const [isAnimating, setIsAnimating] = useState(true);

  
  const signatoriesList = [
    
    "Everything",
    "Everywhere Design",
    "Exeter Waste",
    "F VENZANO",
    "Fairground Studio",
    "Farrah & Pearce Ltd",
    "FearNaught",
    "Fernanda Rizzo",
    "Ferrgood Studio",
    "Few and Far",
    "Fighting Talk Communications",
    "Fiona Watkins Design Limited",
    "Fixperts at Forth",
    "Foundation",
    "Founded Design Ltd",
    "Fourfeet Design",
    "Francesca Cook Design Ltd",
    "Francis Rowland",
    "Frankie Thelwell",
    "FranklinTill",
    "Future Island-Island at Ulster University-led consortium",
    "Future Selves",
    "Futurice Ltd",
    "Fynn",
    "G R Moore Limited",
    "G3 Creative",
    "Gareth Neal Ltd",
    "Gareth Wild",
    "Garlic Agency",
    "Genevieve Bennett Ltd",
    "Genuinely Conscious",
    "George Charnley",
    "George Rowland",
    "GET LOST",
    "Gianfranco Fagotto",
    "Gitta Gschwendtner Ltd",
    "Giulia Villa",
    "Glen Cutwerk",
    "Glimpse",
    "Good Design Works",
    "Good Stuff Creative",
    "Good Will Studios",
    "Goodtale",
    "Goodwin Hartshorn",
    "Graduate Studies at College for Creative Studies",
    "Graft Creative",
    "Green Mat Workshop",
    "Green Orbit Digital",
    "Green Rooms landscapes & gardens",
    "GreenHeights",
    "H&A",
    "Hamish Duncan",
    "Hamish Makgill",
    "Han Li",
    "Hannah Pinnock",
    "Harriet Beesley",
    "Harrison Brands Ltd",
    "Haughton Design",
    "Helen Simmons",
    "Hey Low",
    "Hippo Digital",
    "Hive IT",
    "Hiyield",
    "Holmes Studio",
    "honours",
    "HOUSE OF HACKNEY",
    "Hundred Studio",
    "ICE",
    "ilka design limited",
    "Imagination Factory",
    "Inspirwood",
    "INTRA DRIVE LTD",
    "Irina Teti",
    "Isabella",
    "Jackie Malcolm",
    "Jake Owen",
    "James Kindred",
    "James Tooze",
    "Jamie Pinkham",
    "jan lewis creative",
    "Jane Penty",
    "Jason Bruges Studio",
    "Jason Mesut",
    "Jemima Duncalf",
    "Jess Baxter",
    "Jess Francis",
    "JK Creative Company",
    "Jo Mansfield",
    "Joanna boehnert",
    "John Gilbert",
    "Joseph Folkes",
    "Josh Elgood",
    "Joshua Tunstill",
    "Jude Pullen",
    "Juice by Design",
    "Justine Wyness",
    "Kaelum van der Berg",
    "Kai Davis",
    "Kaleido Grafik",
    "Kanika Kalra",
    "Karishma Kusurkar",
    "Kathryn Summers",
    "Kavya Narayanan",
    "Kenny Heard",
    "Kenwood Design Office (KDO) at Kenwood Limited",
    "Kim Trow",
    "Kinneir Dufort",
    "Kirsten Gord",
    "KLUVERWORKS",
    "Kyle Soo",
    "Kyle Stuart Florent Taylor",
    "Laura Santamaria",
    "Laure Rees-Smith",
    "Lawrence Zeegen",
    "Layerd.Studio",
    "Leap Design",
    "Lewis Plummer",
    "Liam O'Brien",
    "Lil Creative Studio",
    "Limber Brands",
    "Liquid Studio Ltd",
    "Lobo Creative",
    "LowCarbon",
    "Lucy Carruthers",
    "Lucy Watkins",
    "Luigi Gisolfi",
    "Lyon & Lyon",
    "MA Sustainable Design at University of Brighton",
    "Made for the World",
    "madeby.studio",
    "Magnus Long Studio",
    "Mainlyphotography Studio",
    "Mani I",
    "Mantra",
    "Mar Mar Co. Studio",
    "March Studio Ltd",
    "Maria Elina",
    "Marion Ratie",
    "Mark Hicks",
    "Marta De Prisco",
    "MARTA ROSSATO INTERIORS",
    "Martin Hopkins",
    "Martin Price",
    "Martin Wright",
    "Mat Denney",
    "Materialise Interiors",
    "Materials Council",
    "MaterialsInformation Ltd",
    "Matt Hollands",
    "Matteo Menapace",
    "Matter + Perspective",
    "Matthew Kilcullen",
    "Max Fraser",
    "Maya Designer",
    "Mia Allers",
    "Micha Nicheva",
    "Michael James",
    "Michael Love Design",
    "Michael Norrington",
    "Michael Rawling",
    "Midnight",
    "Minna Takala",
    "Mireia Allende",
    "Mitre and Mondays",
    "Mocean",
    "ModularPlastik",
    "Monica Oliveira",
    "MONOMOTIF",
    "Morrama",
    "Muddy Machines",
    "Muta Futures Studio",
    "Nagonic Design Ltd",
    "Naked Ideas",
    "Nat Hunter",
    "Natalia Benusiglio Stern",
    "Natalie Perkins",
    "Nefeli Pavlou Musio",
    "Neol.co",
    "Never Not Ready",
    "Nicola Holden Designs",
    "Nils Aksnes",
    "noel douglas",
    "Norah Joshi (Lewis)",
    "Noughts & Ones",
    "NU Creative Ltd",
    "NU Design Spaces",
    "Nurture",
    "Objective Studio",
    "observerly",
    "Octo Design Ltd",
    "OGRE Studio",
    "Ohana Studio Ltd",
    "Ok deploy",
    "Ole Makkesen Designlab",
    "Olive Kennington",
    "Oliver Lloyd",
    "Olivia Harris",
    "OneKind Creative",
    "Optimist Works",
    "Oracle Design",
    "Orangery",
    "ORCA",
    "Osch",
    "Other Today",
    "OURI Labs",
    "OXygen",
    "Papaya–Studio",
    "Papillon Bleu",
    "Paul Bailey",
    "Paul Gibson Design",
    "Pearson Lloyd",
    "People Planet Product",
    "Phase Two",
    "Pixel Fridge LTD",
    "Pollenize CIC",
    "Polytechnic",
    "Poonum Chauhan",
    "Pretty Clever",
    "Product Design at University of Brighton",
    "Product Design at University of Sussex",
    "Product for Net Zero",
    "Purple Banana",
    "QED web design",
    "Rahul Anand",
    "Realise",
    "Rebekah Di Palma",
    "ReShaped Landscape",
    "Rhapsody Media",
    "Rhombus Studio",
    "Ria Hawthorn",
    "Richa Gandhi",
    "Robin Wong",
    "Roddy Clarke",
    "Rory Cowan",
    "Roundwave",
    "Ruddocks",
    "Ruth Wassermann Ltd",
    "Sabotage",
    "Sam Judge",
    "Samuel Marchant",
    "Sandrine Herbert-Razafinjato",
    "sassd",
    "School of Good Services",
    "Selesti",
    "Selina Rose",
    "Set Studio",
    "Seth Campbell",
    "Sheffield Creative Industries Institute at Sheffield Hallam University",
    "Simone Cucchi",
    "Snook",
    "Social Change",
    "Sophie Mockridge",
    "Sophie Reynolds",
    "Sophie Thomas",
    "Spark & Bell",
    "Special Projects",
    "Spotless",
    "Sruti Gidugu",
    "Standfirst",
    "Stefan Bassing",
    "Still&Nimble",
    "Storo",
    "Straight Forward Design",
    "Stuart Gough",
    "Studio Breuil",
    "Studio Casey Joy",
    "Studio Elk",
    "Studio Elma",
    "Studio Every",
    "Studio Gallant",
    "Studio Joana",
    "Studio KICO",
    "Studio Mothership",
    "Studio Olivers",
    "Studio Ology",
    "Studio Output",
    "Studio Overberg",
    "Studio Simple",
    "Studio Technical Nature",
    "Studio Tom Metcalfe",
    "Studio Wood",
    "Submarine",
    "Substance",
    "Superfried",
    "Susanna Edwards",
    "Susannah Kabuiku",
    "Sustainable Ventures Design",
    "T&B Design",
    "Tacit-Tacit",
    "Takram",
    "TAMART",
    "Tempest",
    "TEN by Anatomy HCD Limited",
    "Teresa Ferreira Studio",
    "Terrarium",
    "The Art and Design Consultancy",
    "The Blooming Platypus",
    "The Creative Bloc",
    "The Digital Creative London Ltd.",
    "The Discourse",
    "THE FOURTH SOLUTION",
    "The Landscape",
    "The Looking Glass",
    "The Manufacturing Technology Centre",
    "Theo Dormer",
    "Think/Do",
    "Thinkpublic",
    "Thom Baker Consultancy",
    "Thomas Baraldi Cassaro",
    "Thomas Wylam",
    "thomas.matthews",
    "Thoughtcraft",
    "Tijana Tasich",
    "Tim Frenneaux & Co",
    "Tina Bernstein",
    "TLC",
    "Tokyo Calm",
    "Tom Greenwood",
    "Tomas Gecim",
    "Tommy Papaioannou",
    "Tria Design",
    "Tristan Palmer Studio",
    "Two",
    "Two Degrees Studio",
    "Tŷ Syml",
    "Unboxed",
    "Unfound Studio",
    "United by Design",
    "UnlikelyGenius",
    "URGE Collective",
    "Vashti Waite",
    "Vestre Ltd",
    "Vicky Lofthouse",
    "Virgile Janssen",
    "Visual Print and Design",
    "VIVID NINE",
    "Vovi",
    "Vox Aeris",
    "Vu Online",
    "We Are Service Works Ltd",
    "We Are Systematic",
    "We Made This Ltd",
    "We Mean This",
    "WEAMO",
    "West9 Design",
    "White Weft Limited",
    "Wholegrain Digital",
    "WizzDev",
    "Working with Joe Ltd",
    "Works in Public Ltd",
  
    "xforwhy",
    "XTATX Studio",
    "Yarn Creative",
    "yesim tuzun",
    "Yoke design",
    "Zebra Growth Limited",
    "Zoe Bather",
    "ZOOZLY"
  ];

 
  useEffect(() => {
    const finalCount = signatoriesList.length;
    let currentCount = 0;
    
    const animateCount = () => {
      const increment = Math.ceil(finalCount / 100);
      const duration = 3; 
      
      const timer = setInterval(() => {
        currentCount += increment;
        if (currentCount >= finalCount) {
          currentCount = finalCount;
          setCount(currentCount);
          setIsAnimating(false);
          clearInterval(timer);
        } else {
          setCount(currentCount);
        }
      }, duration);
      
      return timer;
    };

    const timer = animateCount();
    return () => clearInterval(timer);
  }, [signatoriesList.length]);

  return (
    <div className="grid mt-[17rem] ">
      {/* Header section */}
      <div className="md:p-4">
        <div className="sticky top-7">
          <Heading 
            title={
              <>
                <div className={`text-6xl font-medium transition-all duration-300 text-textColor`}>
                  #{count}
                </div>
                <div className="flex items-center gap-2">
                  <div className="text-[27px]">Global Supporters</div>
                  
                </div>
              </>
            } 
          />
        </div>
      </div>

      {/* Signatories list */}
      <div className="text-textColor mt-20 pb-20 ">
        <div className="grid grid-cols-3 md:grid-cols-6 lg:grid-cols-9 ">
          {signatoriesList.map((signatory, index) => (
            <div 
              key={index} 
              className=" landscape-[2px] text-xs cursor-pointer hover:underline "
        
            >
              {signatory}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Supporters;